import asyncio
import sys
import os

# Ensure backend directory is in path
sys.path.append(os.getcwd())

from app.core.database import SessionLocal
from app.services.feedback_agent import feedback_agent

async def test_integration():
    print("--- Testing Feedback Agent with Real LLM ---")
    
    db = SessionLocal()
    question_text = "What is the primary function of the mitochondria?"
    
    # 1. Test Hint Generation
    print("\n[1] Generating Hint (Level 1)...")
    try:
        result = await feedback_agent.generate_hint(
            db=db,
            question_id="demo-q-1",
            question_text=question_text,
            user_id="demo-user",
            session_id="demo-session",
            hint_level=1
        )
        print(f"Hint Text: {result['hint_text']}")
        if result.get('is_fallback'):
            print("WARNING: Result was generated by fallback mock.")
        else:
            print("SUCCESS: Result generated by Gemini.")
            
    except Exception as e:
        print(f"ERROR: {e}")

    # 2. Test Explanation
    print("\n[2] Generating Explanation...")
    try:
        result = await feedback_agent.generate_explanation(
            db=db,
            question_id="demo-q-1",
            question_text=question_text,
            user_answer="The cell wall",
            correct_answer="Mitochondria",
            user_id="demo-user",
            session_id="demo-session"
        )
        print(f"Explanation: {result['explanation']}")
        print(f"Motivation: {result['motivational_message']}")
        
        if result.get('is_fallback'):
            print("WARNING: Result was generated by fallback mock.")
        else:
             print("SUCCESS: Result generated by Gemini.")

    except Exception as e:
        print(f"ERROR: {e}")
    finally:
        db.close()

if __name__ == "__main__":
    asyncio.run(test_integration())
