export type DistrictId = "SJUSD" | "ESD";
export type SubjectId = "ela" | "math" | "science" | "social_studies";

export type ConceptFamily =
  | "habitats_and_survival"
  | "characters_and_challenges"
  | "government_and_community"
  | "point_of_view"
  | "technology_problem_solving"
  | "stories_and_lessons"
  | "past_and_present"
  | "earth_systems_wind_water"
  | "buyers_and_sellers"
  | "states_of_matter"
  | "friends_and_family"
  | "animal_discoveries"
  | "learning_from_experiences"
  | "community_difference"
  | "changes_over_time"
  | "teamwork"
  | "addition_subtraction_20"
  | "even_odd_arrays_equal_groups"
  | "addition_subtraction_100"
  | "place_value_to_1000"
  | "compare_to_1000"
  | "addition_subtraction_1000"
  | "money_and_data"
  | "length_and_measurement"
  | "time_shapes_fractions_equal_parts"
  | "ecosystems_pollination_seed_dispersal";

export type MechanicFamily = "count_and_compare" | "sort_and_match" | "predict_and_test";

export interface CurriculumEntry {
  district: DistrictId;
  subject: SubjectId;
  gradeLevel: 2;
  curriculum: string;
  code: string;
  title: string;
  conceptFamily: ConceptFamily;
  vocabularyLevel: "low" | "medium";
  maxWordsPerPrompt: number;
  allowedMechanics: MechanicFamily[];
}

export const GRADE2_CURRICULUM: CurriculumEntry[] = [
  {
    district: "SJUSD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "Benchmark Advance",
    code: "SJUSD-G2-ELA-U1",
    title: "Plants and Animals in Their Habitats",
    conceptFamily: "habitats_and_survival",
    vocabularyLevel: "low",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["sort_and_match", "predict_and_test"],
  },
  {
    district: "SJUSD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "Benchmark Advance",
    code: "SJUSD-G2-ELA-U2",
    title: "Characters Facing Challenges",
    conceptFamily: "characters_and_challenges",
    vocabularyLevel: "low",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["sort_and_match", "count_and_compare"],
  },
  {
    district: "SJUSD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "Benchmark Advance",
    code: "SJUSD-G2-ELA-U3",
    title: "Government at Work",
    conceptFamily: "government_and_community",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["sort_and_match", "predict_and_test"],
  },
  {
    district: "SJUSD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "Benchmark Advance",
    code: "SJUSD-G2-ELA-U4",
    title: "Many Characters, Many Points of View",
    conceptFamily: "point_of_view",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["sort_and_match", "predict_and_test"],
  },
  {
    district: "SJUSD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "Benchmark Advance",
    code: "SJUSD-G2-ELA-U5",
    title: "Solving Problems Through Technology",
    conceptFamily: "technology_problem_solving",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["predict_and_test", "sort_and_match"],
  },
  {
    district: "SJUSD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "Benchmark Advance",
    code: "SJUSD-G2-ELA-U6",
    title: "Tales to Live By",
    conceptFamily: "stories_and_lessons",
    vocabularyLevel: "low",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["sort_and_match", "count_and_compare"],
  },
  {
    district: "SJUSD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "Benchmark Advance",
    code: "SJUSD-G2-ELA-U7",
    title: "Investigating the Past",
    conceptFamily: "past_and_present",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["sort_and_match", "predict_and_test"],
  },
  {
    district: "SJUSD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "Benchmark Advance",
    code: "SJUSD-G2-ELA-U8",
    title: "Wind and Water Change Earth",
    conceptFamily: "earth_systems_wind_water",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["predict_and_test", "sort_and_match"],
  },
  {
    district: "SJUSD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "Benchmark Advance",
    code: "SJUSD-G2-ELA-U9",
    title: "Buyers and Sellers",
    conceptFamily: "buyers_and_sellers",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["sort_and_match", "count_and_compare"],
  },
  {
    district: "SJUSD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "Benchmark Advance",
    code: "SJUSD-G2-ELA-U10",
    title: "States of Matter",
    conceptFamily: "states_of_matter",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["predict_and_test", "sort_and_match"],
  },
  {
    district: "SJUSD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "HMH Into Math",
    code: "SJUSD-G2-MATH-M1",
    title: "Addition and Subtraction Situations (within 20)",
    conceptFamily: "addition_subtraction_20",
    vocabularyLevel: "low",
    maxWordsPerPrompt: 16,
    allowedMechanics: ["count_and_compare", "sort_and_match"],
  },
  {
    district: "SJUSD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "HMH Into Math",
    code: "SJUSD-G2-MATH-M2",
    title: "Even and Odd Numbers, Arrays, Equal Groups",
    conceptFamily: "even_odd_arrays_equal_groups",
    vocabularyLevel: "low",
    maxWordsPerPrompt: 16,
    allowedMechanics: ["count_and_compare", "sort_and_match"],
  },
  {
    district: "SJUSD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "HMH Into Math",
    code: "SJUSD-G2-MATH-M3-M5",
    title: "Addition and Subtraction within 100 (Regrouping)",
    conceptFamily: "addition_subtraction_100",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["count_and_compare", "predict_and_test"],
  },
  {
    district: "SJUSD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "HMH Into Math",
    code: "SJUSD-G2-MATH-M6",
    title: "Three-Digit Numbers (Counting to 1,000)",
    conceptFamily: "place_value_to_1000",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["count_and_compare", "sort_and_match"],
  },
  {
    district: "SJUSD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "HMH Into Math",
    code: "SJUSD-G2-MATH-M7",
    title: "Compare Three-Digit Numbers",
    conceptFamily: "compare_to_1000",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["count_and_compare", "sort_and_match"],
  },
  {
    district: "SJUSD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "HMH Into Math",
    code: "SJUSD-G2-MATH-M10",
    title: "Multi-digit Addition (within 1,000)",
    conceptFamily: "addition_subtraction_1000",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["count_and_compare", "predict_and_test"],
  },
  {
    district: "SJUSD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "HMH Into Math",
    code: "SJUSD-G2-MATH-M14",
    title: "Money (coins and bills)",
    conceptFamily: "money_and_data",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["sort_and_match", "count_and_compare"],
  },
  {
    district: "SJUSD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "HMH Into Math",
    code: "SJUSD-G2-MATH-M18",
    title: "Length and Measurement",
    conceptFamily: "length_and_measurement",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["count_and_compare", "predict_and_test"],
  },
  {
    district: "ESD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "McGraw Hill Wonders",
    code: "ESD-G2-ELA-U1",
    title: "Friends and Family",
    conceptFamily: "friends_and_family",
    vocabularyLevel: "low",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["sort_and_match", "predict_and_test"],
  },
  {
    district: "ESD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "McGraw Hill Wonders",
    code: "ESD-G2-ELA-U2",
    title: "Animal Discoveries",
    conceptFamily: "animal_discoveries",
    vocabularyLevel: "low",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["sort_and_match", "predict_and_test"],
  },
  {
    district: "ESD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "McGraw Hill Wonders",
    code: "ESD-G2-ELA-U3",
    title: "Live and Learn",
    conceptFamily: "learning_from_experiences",
    vocabularyLevel: "low",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["sort_and_match", "count_and_compare"],
  },
  {
    district: "ESD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "McGraw Hill Wonders",
    code: "ESD-G2-ELA-U4",
    title: "Our Community",
    conceptFamily: "community_difference",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["sort_and_match", "predict_and_test"],
  },
  {
    district: "ESD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "McGraw Hill Wonders",
    code: "ESD-G2-ELA-U5",
    title: "Changes Over Time",
    conceptFamily: "changes_over_time",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["predict_and_test", "sort_and_match"],
  },
  {
    district: "ESD",
    subject: "ela",
    gradeLevel: 2,
    curriculum: "McGraw Hill Wonders",
    code: "ESD-G2-ELA-U6",
    title: "Team Up!",
    conceptFamily: "teamwork",
    vocabularyLevel: "low",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["sort_and_match", "count_and_compare"],
  },
  {
    district: "ESD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "Eureka Math",
    code: "ESD-G2-MATH-M1",
    title: "Sums and Differences to 20",
    conceptFamily: "addition_subtraction_20",
    vocabularyLevel: "low",
    maxWordsPerPrompt: 16,
    allowedMechanics: ["count_and_compare", "predict_and_test"],
  },
  {
    district: "ESD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "Eureka Math",
    code: "ESD-G2-MATH-M2",
    title: "Addition and Subtraction of Length Units",
    conceptFamily: "length_and_measurement",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["count_and_compare", "predict_and_test"],
  },
  {
    district: "ESD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "Eureka Math",
    code: "ESD-G2-MATH-M3",
    title: "Place Value, Counting, and Comparison to 1,000",
    conceptFamily: "place_value_to_1000",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["count_and_compare", "sort_and_match"],
  },
  {
    district: "ESD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "Eureka Math",
    code: "ESD-G2-MATH-M4",
    title: "Addition and Subtraction Within 200",
    conceptFamily: "addition_subtraction_100",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["count_and_compare", "predict_and_test"],
  },
  {
    district: "ESD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "Eureka Math",
    code: "ESD-G2-MATH-M5",
    title: "Addition and Subtraction Within 1,000",
    conceptFamily: "addition_subtraction_1000",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["count_and_compare", "predict_and_test"],
  },
  {
    district: "ESD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "Eureka Math",
    code: "ESD-G2-MATH-M6",
    title: "Foundations of Multiplication and Division (Equal Groups)",
    conceptFamily: "even_odd_arrays_equal_groups",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["count_and_compare", "sort_and_match"],
  },
  {
    district: "ESD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "Eureka Math",
    code: "ESD-G2-MATH-M7",
    title: "Problem Solving with Length, Money, and Data",
    conceptFamily: "money_and_data",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["count_and_compare", "sort_and_match"],
  },
  {
    district: "ESD",
    subject: "math",
    gradeLevel: 2,
    curriculum: "Eureka Math",
    code: "ESD-G2-MATH-M8",
    title: "Time, Shapes, and Fractions as Equal Parts of Shapes",
    conceptFamily: "time_shapes_fractions_equal_parts",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 18,
    allowedMechanics: ["sort_and_match", "predict_and_test"],
  },
  {
    district: "SJUSD",
    subject: "science",
    gradeLevel: 2,
    curriculum: "NGSS",
    code: "SCI-G2-ECOSYSTEMS",
    title: "Interdependent Relationships in Ecosystems",
    conceptFamily: "ecosystems_pollination_seed_dispersal",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["sort_and_match", "predict_and_test"],
  },
  {
    district: "SJUSD",
    subject: "science",
    gradeLevel: 2,
    curriculum: "NGSS",
    code: "SCI-G2-EARTH-SYSTEMS",
    title: "Earth's Systems: Processes that Shape the Earth",
    conceptFamily: "earth_systems_wind_water",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["predict_and_test", "count_and_compare"],
  },
  {
    district: "SJUSD",
    subject: "science",
    gradeLevel: 2,
    curriculum: "NGSS",
    code: "SCI-G2-MATTER",
    title: "Structure and Properties of Matter",
    conceptFamily: "states_of_matter",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["predict_and_test", "sort_and_match"],
  },
  {
    district: "ESD",
    subject: "science",
    gradeLevel: 2,
    curriculum: "NGSS",
    code: "SCI-G2-ECOSYSTEMS",
    title: "Interdependent Relationships in Ecosystems",
    conceptFamily: "ecosystems_pollination_seed_dispersal",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["sort_and_match", "predict_and_test"],
  },
  {
    district: "ESD",
    subject: "science",
    gradeLevel: 2,
    curriculum: "NGSS",
    code: "SCI-G2-EARTH-SYSTEMS",
    title: "Earth's Systems: Processes that Shape the Earth",
    conceptFamily: "earth_systems_wind_water",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["predict_and_test", "count_and_compare"],
  },
  {
    district: "ESD",
    subject: "science",
    gradeLevel: 2,
    curriculum: "NGSS",
    code: "SCI-G2-MATTER",
    title: "Structure and Properties of Matter",
    conceptFamily: "states_of_matter",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["predict_and_test", "sort_and_match"],
  },
  {
    district: "SJUSD",
    subject: "social_studies",
    gradeLevel: 2,
    curriculum: "Local Social Studies",
    code: "SJUSD-G2-SS-PEOPLE-DIFFERENCE",
    title: "People Who Make a Difference",
    conceptFamily: "community_difference",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["sort_and_match", "predict_and_test"],
  },
  {
    district: "ESD",
    subject: "social_studies",
    gradeLevel: 2,
    curriculum: "SEAL Integrated Social Studies",
    code: "ESD-G2-SS-COMMUNITY",
    title: "Community and Civic Participation",
    conceptFamily: "government_and_community",
    vocabularyLevel: "medium",
    maxWordsPerPrompt: 20,
    allowedMechanics: ["sort_and_match", "count_and_compare"],
  },
];

export const KINDERGARTEN_CURRICULUM = GRADE2_CURRICULUM;

export function getCurriculumEntry(code: string): CurriculumEntry | undefined {
  return GRADE2_CURRICULUM.find((entry) => entry.code === code);
}

export function getCurriculumByDistrict(district: DistrictId): CurriculumEntry[] {
  return GRADE2_CURRICULUM.filter((entry) => entry.district === district);
}

export function getCurriculumByDistrictAndSubject(
  district: DistrictId,
  subject: SubjectId
): CurriculumEntry[] {
  return GRADE2_CURRICULUM.filter(
    (entry) => entry.district === district && entry.subject === subject
  );
}